image: node:12

stages:
  - build
  - deploy

cache:
  paths:
    - front/node_modules/

build:
  stage: build
  script:
    - cd front
    - npm install
    - CI= npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - front/build
  only:
    - release

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 sync front/build s3://connectclass.io --acl public-read
  only:
    - release