stages:
  - back-deploy

variables:
  IMAGE_NAME: connectclass-back
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - back/node_modules/

back-deploy:
  stage: package
  stage: back-deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd back
    - docker build . -t $IMAGE_NAME
    - docker ps -q --filter "name=$IMAGE_NAME" | grep -q . && docker stop $IMAGE_NAME && docker rm $IMAGE_NAME || true
    - docker run -d -p 8080:8080 --name $IMAGE_NAME --restart always $IMAGE_NAME
    - docker container ls -a
