image: node:12

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
 
stages:
  - build
  - deploy
cache:
  paths:
  - node_modules/
build:
  only:
    - release
  stage: build
  script:
    - cd front
    - npm install
    - npm run build
deploy:
  only:
    - release
  stage: deploy
  script:
    - cd front
    - npm run deploy