image: node:12

stages:
  - build
  - deploy

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  REACT_APP_QUESTION_LAYER: $QUESTION_LAYER
  REACT_APP_VALIDATION_LAYER: $VALIDATION_LAYER
  REACT_APP_STUDY_LAYER: $STUDY_LAYER
  REACT_APP_DB_LAYER: $DB_LAYER
  REACT_APP_AUTH_LAYER: $AUTH_LAYER
  REACT_APP_UPLOAD_LAYER: $UPLOAD_LAYER
  REACT_APP_KAKAO_KEY: $KAKAO_KEY
  REACT_APP_NAVER_KEY: $NAVER_KEY
  REACT_APP_GOOGLE_KEY: $GOOGLE_KEY
  REACT_APP_NAVER_SECRET_KEY: $NAVER_SECRET_KEY
  REACT_APP_NAVER_STATE: $NAVER_STATE
  REACT_APP_NAVER_APP_KEY: $NAVER_APP_KEY

cache:
  paths:
    - front/node_modules/

build:
  stage: build
  script:
    - cd front
    - npm install
    - CI= npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - front/build
  only:
    - release
  tags:
    - ci

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 cp --recursive --region ap-northeast-2 front/build/ s3://connectclass.io
  only:
    - release
  tags:
    - ci
