stages:
  - back-build
  - back-deploy

variables:
  IMAGE_NAME: connectclass-back
  DOCKER_HOST: tcp://docker:2375

cache:
  paths:
    - back/node_modules/

back-build:
  stage: back-build
  image: docker:latest
  services:
    - docker:19.03.8-dind
  script:
    - cd back
    - docker build . -t $IMAGE_NAME

back-deploy:
  stage: back-deploy
  image: docker:latest
  services:
    - docker:19.03.8-dind
  script:
    - docker container rm -f connectclass-back
    - docker run -d -p 8080:8080 --name connectclass-back --restart always $IMAGE_NAME
