stages:
  - test
  - deploy

variables:
  PROJECT_NAME: connectclass-back
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - back/node_modules/

test:
  stage: test
  image: node:12
  script:
    - cd back
    - npm install

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd back
    - docker build . -t $PROJECT_NAME
    - docker ps -q --filter "name=$PROJECT_NAME" | grep -q . && docker stop $PROJECT_NAME && docker rm $PROJECT_NAME || true
    - docker run -d -p 8080:8080 --name nodejs-server --restart always $PROJECT_NAME
    - docker container ls -a
