image: node:12

stages:
  - build
  - deploy
  
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

cache:
  paths:
    - front/node_modules/

build:
  stage: build
  script:
    - cd front
    - npm install
    - CI= npm run build
  artifacts:
    expire_in: 1 hour
    paths:
      - front/build
  only:
    - release

deploy:
  image: python:latest
  stage: deploy
  script:
    - pip install awscli
    - aws s3 cp --recursive --region ap-northeast-2 front/build/ s3://connectclass.io
  only:
    - release